name = "light_heart"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_http = "~> 3.5"
gleam_erlang = "~> 0.22"
gleam_crypto = "~> 1.0"
mist = "~> 0.14"
sqlight = "~> 0.9"
wisp = "~> 0.5"

envoy = "~> 1.0"
argv = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
